apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resnet50-dataset
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-provisioner
