apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: openshift-masters-performance-profile
spec:
  additionalKernelArgs:
  - rcupdate.rcu_normal_after_boot=0
  - efi=runtime
  - module_blacklist=irdma
  cpu:
    isolated: 8-111
    reserved: 0-7
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 16
      node: 0
      size: 1G
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
