apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: fine-tuning
  namespace: fine-tuning-testing
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations: &annotations
            k8s.v1.cni.cncf.io/networks: |-
              [
                {
                  "name": "network-port-1",
                  "namespace": "default"
                }
              ]
        spec:
          containers:
            - name: pytorch
              image: path.to.image
              imagePullPolicy: Always
              env: &env
                - name: NCCL_DEBUG
                  value: "INFO"
                - name: NCCL_IGNORE_CPU_AFFINITY
                  value: "1"
                - name: NCCL_CROSS_NIC
                  value: "0"
                - name: NCCL_SOCKET_IFNAME
                  value: "net1"
                - name: NCCL_IB_QPS_PER_CONNECTION
                  value: "1"
                - name: SHARED_PATH
                  value: "/mnt/storage"
                - name: BACKEND
                  value: "nccl"
                - name: BATCH_SIZE
                  value: "128"
                - name: DATA_PATH
                  value: "/mnt/storage/dataset/cifar10_imagefolder"
                - name: NUM_TRAIN_EPOCHS
                  value: "1"
                - name: LEARNING_RATE
                  value: "0.001"
                - name: NUM_WORKERS
                  value: "6"
                - name: PRINT_INTERVAL
                  value: "5"
                - name: NNODES
                  value: "3"
                - name: NPROC_PER_NODE
                  value: "1"
                - name: MASTER_PORT
                  value: "23456"
                - name: NETWORK_INTERFACE
                  value: "net1"
                - name: OUTPUT_DIR
                  value: "/mnt/storage/"
              volumeMounts: &vol_mount
                - name: storage-volume
                  mountPath: /mnt/storage
                - name: shm-volume
                  mountPath: /dev/shm
                - name: shared-volume
                  mountPath: /mnt/shared
              resources: &resource_req
                requests:
                  nvidia.com/gpu: "1"
                  memory: "10Gi"
                  cpu: "1"
                  openshift.io/port1: "1"
                limits:
                  nvidia.com/gpu: "1"
                  openshift.io/port1: "1"
              securityContext: &sec_profile
                runAsUser: 0
                runAsGroup: 0
                capabilities:
                  add: ["IPC_LOCK", "SYS_RESOURCE", "NET_RAW", "SYS_CHROOT", "AUDIT_WRITE"]
              command: ["/workspace/training/entrypoint.sh"]
          volumes: &vols
            - name: storage-volume
              persistentVolumeClaim:
                claimName: res50-storage
            - name: shm-volume
              emptyDir:
                medium: Memory
                sizeLimit: 10Gi
            - name: shared-volume
              emptyDir: {}
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          annotations: *annotations
        spec:
          containers:
            - name: pytorch
              image: path.to.image
              imagePullPolicy: Always
              env: *env
              volumeMounts: *vol_mount
              resources: *resource_req
              securityContext: *sec_profile
              command: ["/workspace/training/entrypoint.sh"]
          volumes: *vols
